name: CI/CD Pipeline On PR Merged

on:
   [pull_request]
    # push:
    #     branches:
    #       - main

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Create user.csv
        run: |
          touch user.csv
          echo "${{secrets.USER_CSV}}" >> user.csv

      - name: Build application artifact
        run: zip -r webapp.zip .   
      
      - name: list files
        run: ls -al
        
      - name: Configure AWS credentials dev
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}   
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Initialize packer configuration
        run: packer init webapp.pkr.hcl
        
      - name: Build AMI with Packer
        run: |
            PACKER_OUTPUT=$(packer build webapp.pkr.hcl)
            AMI_ID=$(echo "$PACKER_OUTPUT" | grep -oP 'AMI: \K(ami-[a-zA-Z0-9]+)')
            echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
            echo "::set-output name=ami_id::$AMI_ID"
        env:
          PKR_VAR_database_pass: ${{secrets.DB_PASSWORD}} 
          PKR_VAR_database_user: ${{secrets.DB_USERNAME}}
          PKR_VAR_database_host: ${{secrets.DB_HOST}} 
          PKR_VAR_aws_region: "${{secrets.AWS_REGION}}"
          PKR_VAR_source_ami: "${{secrets.SOURCE_AMI}}"
          PKR_VAR_subnet_id: "${{secrets.SUBNET_ID}}"

      
      - name: Configure AWS credentials demo
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_DEMO }}   
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_DEMO }}
          aws-region: us-east-1

      # Create New Launch Template Version in the Demo account
      - name: Create New Launch Template Version
        run: |
          latest_version=$(aws ec2 describe-launch-template-versions --launch-template-name csyeA10LaunchTemplate --query 'LaunchTemplateVersions[-1].VersionNumber' --output text)
          aws ec2 create-launch-template-version --launch-template-name csyeA10LaunchTemplate --source-version $latest_version --launch-template-data "{\"ImageId\":\"${{ env.AMI_ID}}\"}"


      # Update Autoscaling Group with the new Launch Template version
      - name: Update Autoscaling Group
        run: |
          latest_version=$(aws ec2 describe-launch-template-versions --launch-template-name csyeA10LaunchTemplate --query 'LaunchTemplateVersions[-1].VersionNumber' --output text)
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name csyeA10AutoScalingGroup --launch-template "LaunchTemplateName=csyeA10LaunchTemplate,Version=$latest_version"



      # Instance Refresh for the Autoscaling Group
      - name: Instance Refresh
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name csyeA10AutoScalingGroup
