name: CI/CD Pipeline On PR Merged

on:
    push:
        branches:
          - main

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: Build application artifact
        run: zip -r webapp.zip .   
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}   
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Initialize packer configuration
        run: packer init webapp.pkr.hcl
        
      - name: Build AMI with Packer
        run: packer build webapp.pkr.hcl
        
    
