name: CI/CD Pipeline On PR Merged

on:
    push:
        branches:
          - main

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Create Environment File
        run: |
          touch .env
          echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> .env
          echo "DB_NAME=${{secrets.DB_NAME}}" >> .env
          echo "DB_USERNAME=${{secrets.DB_USERNAME}}" >> .env
          echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
          echo "DB_HOST=${{secrets.DB_HOST}}" >> .env
          echo "DB_DIALECT=${{secrets.DIALECT}}" >> .env
          echo "DEFAULTUSERPATH=${{secrets.DEFAULTUSERPATH}}" >> .env

      - name: Create user.csv
        run: |
          touch user.csv
          echo "${{secrets.USER_CSV}}" >> user.csv

      - name: Build application artifact
        run: zip -r webapp.zip .   
      
      - name: list files
        run: ls -al
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}   
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Initialize packer configuration
        run: packer init webapp.pkr.hcl
        
      - name: Build AMI with Packer
        run: packer build webapp.pkr.hcl
        
    
