name: Validate Packer Template

on:
  [pull_request]


jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize packer configuration
        run: packer init webapp.pkr.hcl

      - name: Format template
        run: packer fmt webapp.pkr.hcl

      - name: Validate template
        run: packer validate webapp.pkr.hcl
