name: Validate Packer Template

on:
  [pull_request]


jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build application artifact
        run: zip -r webapp.zip . 
        
      - name: Initialize packer configuration
        run: packer init webapp.pkr.hcl

      - name: Format template
        id: fmt
        run: |
          set -e
          if ! packer fmt webapp.pkr.hcl; then
            echo "Template is not formatted correctly. Please run 'packer fmt' locally and push the changes."
            exit 1
          fi

      - name: Validate template
        run: packer validate webapp.pkr.hcl

      